- hosts: all
  gather_facts: no
  become: yes
  become_user: root

  roles:
      - network

- hosts: smn
  gather_facts: no
  become: yes
  become_user: root

  tasks:
  - include_vars: user-access.yml

  - name: create SSH proxy user
    user:
      name: '{{ user_name }}'
      generate_ssh_key: '{{ ansible_hostname == "smn" }}'
      
- hosts:
  - smn
  - uan
  become: yes
  become_user: root

  tasks:
  - include_vars: user-access.yml

  - name: create SSH proxy user
    user:
      name: '{{ user_name }}'
      
  - name: ensure existence of SSH directory
    file:
      path: /home/{{ user_name }}/.ssh
      state: directory
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0700

  - name: add public key to authorized keys
    authorized_key:
      user: '{{ user_name }}'
      key: '{{ public_key_content }}'

  - name: copy private key of SSH proxy user
    copy:
      src: '{{ private_key }}'
      dest: /home/{{ user_name }}/.ssh
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0600

