- hosts: all
  gather_facts: no
  become: yes
  become_user: root

  roles:
      - role: network
        network_interfaces_file_name: 50-cloud-init.cfg

- hosts: smn
  gather_facts: no
  become: yes
  become_user: root

  tasks:
  - name: get interface of default gateway
    shell: ip route list | grep ^default | grep -oP '(?<=dev )[^ ]+'
    changed_when: False
    register: default_gateway

  - set_fact:
      default_gateway: '{{ default_gateway.stdout }}'

  - name: setup NAT
    iptables:
      chain: POSTROUTING
      out_interface: '{{ default_gateway }}'
      table: nat
      jump: MASQUERADE

  - include_vars: user-access.yml

  - name: create SSH proxy user
    user:
      name: '{{ user_name }}'
      generate_ssh_key: yes

- hosts:
  - smn
  - uan
  gather_facts: no
  become: yes
  become_user: root

  tasks:
  - include_vars: user-access.yml

  - name: create SSH proxy user
    user:
      name: '{{ user_name }}'
      
  - name: ensure existence of SSH directory
    file:
      path: /home/{{ user_name }}/.ssh
      state: directory
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0700

  - name: add public key to authorized keys
    authorized_key:
      user: '{{ user_name }}'
      key: '{{ public_key_content }}'

  - name: copy private key of SSH proxy user
    copy:
      src: '{{ private_key }}'
      dest: /home/{{ user_name }}/.ssh
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0600

