- name: Deploy blackbox-exporter & prometheus on man
  hosts: "{{ 'man' if run else omit }}"
  become: true
  vars:
    run: >
        {{ (groups['monitor-os'] is defined) or
        (groups['monitor-icmp'] is defined) or
        (groups['monitored_hosts_tcp'] is defined and (groups['monitored_hosts_tcp'] | length > 0)) or
        (groups['monitored_hosts_icmp'] is defined and (groups['monitored_hosts_icmp'] | length > 0)) or
        (monitoring_http_targets is defined and (monitoring_http_targets | length > 0)) }}
  roles:
    - role: prometheus
    - role: blackbox-exporter

- name: Deploy node-exporter on Linux hosts
  hosts: "{{ 'monitor-os:!windows_hosts' if run_listed else 'routers:hosts:!proxy-jump:!windows_hosts' if run_all else omit }}"
  become: true
  strategy: host_pinned
  vars:
    run_listed: "{{ groups['monitor-os'] is defined and (groups['monitor-os'] | length > 0) }}"
    run_all: "{{ groups['monitor-os'] is defined and (groups['monitor-os'] | length == 0) }}"
  roles:
    - role: node-exporter
      when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'FreeBSD'

- name: Deploy windows-exporter on Windows hosts
  hosts: "{{ 'monitor-os:&windows_hosts' if run_listed else 'windows_hosts' if run_all else omit }}"
  vars:
    run_listed: "{{ groups['monitor-os'] is defined and (groups['monitor-os'] | length > 0) }}"
    run_all: "{{ groups['monitor-os'] is defined and (groups['monitor-os'] | length == 0) }}"
  roles:
    - role: windows-exporter
