
- src: git@gitlab.ics.muni.cz:CSIRT-MU-public/ansible-roles/interface.git
  scm: git
  version: 2-refactoring

- src: git@gitlab.ics.muni.cz:CSIRT-MU-public/ansible-roles/kypo-user-access.git
  scm: git

