- name: blackbox-exporter
  src: https://github.com/cyberrangecz/ansible-role-blackbox-exporter.git
  scm: git
  version: v1.0.0
- name: common
  src: https://github.com/cyberrangecz/ansible-role-common.git
  scm: git
  version: v1.0.0
- name: docker
  src: https://github.com/cyberrangecz/ansible-role-docker.git
  scm: git
  version: v1.0.0
- name: docker-compose
  src: https://github.com/cyberrangecz/ansible-role-docker-compose.git
  scm: git
  version: v1.0.0
- name: guacamole
  src: https://github.com/cyberrangecz/ansible-role-guacamole.git
  scm: git
  version: v1.0.0
- name: interface
  src: https://github.com/cyberrangecz/ansible-role-interface.git
  scm: git
  version: v1.0.0
- name: iptables
  src: https://github.com/cyberrangecz/ansible-role-iptables.git
  scm: git
  version: v1.0.0
- name: k3s
  src: https://github.com/cyberrangecz/ansible-role-k3s.git
  scm: git
  version: v1.0.0
- name: man-logging-forward
  src: https://github.com/cyberrangecz/ansible-role-man-logging-forward.git
  scm: git
  version: v1.0.0
- name: node-exporter
  src: https://github.com/cyberrangecz/ansible-role-node-exporter.git
  scm: git
  version: v1.0.0
- name: prometheus
  src: https://github.com/cyberrangecz/ansible-role-prometheus.git
  scm: git
  version: v1.0.0
- name: user-access
  src: https://github.com/cyberrangecz/ansible-role-user-access.git
  scm: git
  version: v1.0.0
- name: user-access-windows
  src: https://github.com/cyberrangecz/ansible-role-user-access-windows.git
  scm: git
  version: v1.0.0
- name: windows-exporter
  src: https://github.com/cyberrangecz/ansible-role-windows-exporter.git
  scm: git
  version: v1.0.0
